<div class="container">

<table style="width: 100%;"><tr>
<td>try_pipeline_func_call</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>Custom tryCatch configuration for pipeline segment segment functions</h2>

<h3>Description</h3>

<p>Custom tryCatch configuration for pipeline segment segment functions
</p>


<h3>Usage</h3>

<pre><code class="language-R">try_pipeline_func_call(.f, arg, func_name)
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>.f</code></td>
<td>
<p>Pipleine segment function</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>arg</code></td>
<td>
<p>Arguement of <code>.f</code></p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>func_name</code></td>
<td>
<p>(Character string).</p>
</td>
</tr>
</table>
<h3>Value</h3>

<p>Returns the same object as .f does (a data.frame or model object), unless an error is
thrown.
</p>


<h3>Examples</h3>

<pre><code class="language-R">## Not run: 
data &lt;- data.frame(x = 1:3, y = 1:3 / 10)
f &lt;- function(df) data.frame(p = df$x ^ 2, q = df$wrong)
try_pipeline_func_call(f, data, "f")
# Error in data.frame(p = df$x^2, q = df$wrong) :
#   arguments imply differing number of rows: 3, 0
# --&gt; called from within function: f

## End(Not run)
</code></pre>


</div>